stages:
  - build
  - test

.export_build_jdk: &export_build_jdk
  - export JAVA_HOME=$CI_PROJECT_DIR/build/linux-x86_64-normal-zero-release/images/j2sdk-image

cache:
  paths:
    - build/linux-x86_64-normal-zero-release/images/j2sdk-image
    - concolic-test/.gradle/caches
    - concolic-test/.gradle/wrapper

build-jdk:
  stage: build
  script:
    - ./scripts/configure-ci.sh
    - make clean JOBS=24 CONF=linux-x86_64-normal-zero-release
    - make hotspot jdk images JOBS=30 CONF=linux-x86_64-normal-zero-release

test-unit:
  stage: test
  script:
    - cd concolic-test
    - *export_build_jdk
    - ./gradlew test --info

