DROP PROCEDURE IF EXISTS `Purchase_sp_6_ver0`;
DELIMITER $$
CREATE PROCEDURE Purchase_sp_6_ver0 (IN M_L_String__order_com_salesmanager_shop_model_order_v1_PersistableOrder_currency VARCHAR(512))
BEGIN

DECLARE QUERY_ID_0_TXN INT DEFAULT NULL;
DECLARE QUERY_ID_1_TXN INT DEFAULT NULL;
DECLARE q3_i1 VARCHAR(512) DEFAULT NULL;
DECLARE QUERY_ID_2 INT DEFAULT NULL;
DECLARE M_I_RS_23_size INT DEFAULT NULL;
DECLARE cursor_cnt_2 INT DEFAULT NULL;

IF TRUE THEN
commit;
END IF;
IF TRUE THEN
SET QUERY_ID_0_TXN = 0;
set autocommit=1;
END IF;
IF TRUE THEN
SET QUERY_ID_1_TXN = 1;
set autocommit=0;
END IF;
IF TRUE THEN
SET q3_i1 = M_L_String__order_com_salesmanager_shop_model_order_v1_PersistableOrder_currency;
SET QUERY_ID_2 = 2;
SELECT currency0_.CURRENCY_ID AS CURRENCY1_8_, currency0_.CURRENCY_CODE AS CURRENCY2_8_, currency0_.CURRENCY_CURRENCY_CODE AS CURRENCY3_8_, currency0_.CURRENCY_NAME AS CURRENCY4_8_, currency0_.CURRENCY_SUPPORTED AS CURRENCY5_8_ FROM CURRENCY currency0_ WHERE currency0_.CURRENCY_CODE = q3_i1;
SET M_I_RS_23_size = FOUND_ROWS();
END IF;
SELECT QUERY_ID_0_TXN,QUERY_ID_1_TXN,QUERY_ID_2,q3_i1;

END $$
DELIMITER ;