DROP PROCEDURE IF EXISTS `Purchase_sp_30_ver0`;
DELIMITER $$
CREATE PROCEDURE Purchase_sp_30_ver0 ()
BEGIN

DECLARE QUERY_ID_0_TXN INT DEFAULT NULL;
DECLARE QUERY_ID_1_TXN INT DEFAULT NULL;

IF TRUE THEN
commit;
END IF;
IF TRUE THEN
SET QUERY_ID_0_TXN = 0;
set autocommit=1;
END IF;
IF TRUE THEN
SET QUERY_ID_1_TXN = 1;
set autocommit=0;
END IF;
SELECT QUERY_ID_0_TXN,QUERY_ID_1_TXN;

END $$
DELIMITER ;