SqlNo=38
SQLNode {
    sqlTemplate='set autocommit=1',
    parameters={},
    retVals={}
}
SqlNo=39
SQLNode {
    sqlTemplate='set autocommit=0',
    parameters={},
    retVals={}
}
SqlNo=40
SQLNode {
    sqlTemplate='SELECT digitalpro0_.PRODUCT_DIGITAL_ID AS PRODUCT_1_49_0_, product1_.PRODUCT_ID AS PRODUCT_1_44_1_, merchantst2_.MERCHANT_ID AS MERCHANT1_29_2_, digitalpro0_.PRODUCT_ID AS PRODUCT_3_49_0_, digitalpro0_.FILE_NAME AS FILE_NAM2_49_0_ , product1_.DATE_CREATED AS DATE_CRE2_44_1_, product1_.DATE_MODIFIED AS DATE_MOD3_44_1_, product1_.UPDT_ID AS UPDT_ID4_44_1_, product1_.AVAILABLE AS AVAILABL5_44_1_, product1_.COND AS COND6_44_1_ , product1_.DATE_AVAILABLE AS DATE_AVA7_44_1_, product1_.MANUFACTURER_ID AS MANUFAC25_44_1_, product1_.MERCHANT_ID AS MERCHAN26_44_1_, product1_.CUSTOMER_ID AS CUSTOME27_44_1_, product1_.PREORDER AS PREORDER8_44_1_ , product1_.PRODUCT_HEIGHT AS PRODUCT_9_44_1_, product1_.PRODUCT_FREE AS PRODUCT10_44_1_, product1_.PRODUCT_LENGTH AS PRODUCT11_44_1_, product1_.QUANTITY_ORDERED AS QUANTIT12_44_1_, product1_.REVIEW_AVG AS REVIEW_13_44_1_ , product1_.REVIEW_COUNT AS REVIEW_14_44_1_, product1_.PRODUCT_SHIP AS PRODUCT15_44_1_, product1_.PRODUCT_VIRTUAL AS PRODUCT16_44_1_, product1_.PRODUCT_WEIGHT AS PRODUCT17_44_1_, product1_.PRODUCT_WIDTH AS PRODUCT18_44_1_ , product1_.REF_SKU AS REF_SKU19_44_1_, product1_.RENTAL_DURATION AS RENTAL_20_44_1_, product1_.RENTAL_PERIOD AS RENTAL_21_44_1_, product1_.RENTAL_STATUS AS RENTAL_22_44_1_, product1_.SKU AS SKU23_44_1_ , product1_.SORT_ORDER AS SORT_OR24_44_1_, product1_.TAX_CLASS_ID AS TAX_CLA28_44_1_, product1_.PRODUCT_TYPE_ID AS PRODUCT29_44_1_, merchantst2_.DATE_CREATED AS DATE_CRE2_29_2_, merchantst2_.DATE_MODIFIED AS DATE_MOD3_29_2_ , merchantst2_.UPDT_ID AS UPDT_ID4_29_2_, merchantst2_.STORE_CODE AS STORE_CO5_29_2_, merchantst2_.CONTINUESHOPPINGURL AS CONTINUE6_29_2_, merchantst2_.COUNTRY_ID AS COUNTRY24_29_2_, merchantst2_.CURRENCY_ID AS CURRENC25_29_2_ , merchantst2_.CURRENCY_FORMAT_NATIONAL AS CURRENCY7_29_2_, merchantst2_.LANGUAGE_ID AS LANGUAG26_29_2_, merchantst2_.DOMAIN_NAME AS DOMAIN_N8_29_2_, merchantst2_.IN_BUSINESS_SINCE AS IN_BUSIN9_29_2_, merchantst2_.INVOICE_TEMPLATE AS INVOICE10_29_2_ , merchantst2_.PARENT_ID AS PARENT_27_29_2_, merchantst2_.IS_RETAILER AS IS_RETA11_29_2_, merchantst2_.SEIZEUNITCODE AS SEIZEUN12_29_2_, merchantst2_.STORE_EMAIL AS STORE_E13_29_2_, merchantst2_.STORE_LOGO AS STORE_L14_29_2_ , merchantst2_.STORE_TEMPLATE AS STORE_T15_29_2_, merchantst2_.STORE_ADDRESS AS STORE_A16_29_2_, merchantst2_.STORE_CITY AS STORE_C17_29_2_, merchantst2_.STORE_NAME AS STORE_N18_29_2_, merchantst2_.STORE_PHONE AS STORE_P19_29_2_ , merchantst2_.STORE_POSTAL_CODE AS STORE_P20_29_2_, merchantst2_.STORE_STATE_PROV AS STORE_S21_29_2_, merchantst2_.USE_CACHE AS USE_CAC22_29_2_, merchantst2_.WEIGHTUNITCODE AS WEIGHTU23_29_2_, merchantst2_.ZONE_ID AS ZONE_ID28_29_2_ FROM PRODUCT_DIGITAL digitalpro0_ INNER JOIN PRODUCT product1_ ON digitalpro0_.PRODUCT_ID = product1_.PRODUCT_ID INNER JOIN MERCHANT_STORE merchantst2_ ON product1_.MERCHANT_ID = merchantst2_.MERCHANT_ID WHERE merchantst2_.MERCHANT_ID = ? AND product1_.PRODUCT_ID = ?',
    parameters={RS_q2_r1_col2:INT, RS_q19_r1_col1:BIGINT},
    retVals={digitalpro0_.product_digital_id:BIGINT, product1_.product_id:BIGINT, merchantst2_.merchant_id:INT, digitalpro0_.product_id:BIGINT, digitalpro0_.file_name:VARCHAR, product1_.date_created:DATETIME, product1_.date_modified:DATETIME, product1_.updt_id:VARCHAR, product1_.available:BIT, product1_.cond:INT, product1_.date_available:DATETIME, product1_.manufacturer_id:BIGINT, product1_.merchant_id:INT, product1_.customer_id:BIGINT, product1_.preorder:BIT, product1_.product_height:DECIMAL, product1_.product_free:BIT, product1_.product_length:DECIMAL, product1_.quantity_ordered:INT, product1_.review_avg:DECIMAL, product1_.review_count:INT, product1_.product_ship:BIT, product1_.product_virtual:BIT, product1_.product_weight:DECIMAL, product1_.product_width:DECIMAL, product1_.ref_sku:VARCHAR, product1_.rental_duration:INT, product1_.rental_period:INT, product1_.rental_status:INT, product1_.sku:VARCHAR, product1_.sort_order:INT, product1_.tax_class_id:BIGINT, product1_.product_type_id:BIGINT, merchantst2_.date_created:DATETIME, merchantst2_.date_modified:DATETIME, merchantst2_.updt_id:VARCHAR, merchantst2_.store_code:VARCHAR, merchantst2_.continueshoppingurl:VARCHAR, merchantst2_.country_id:INT, merchantst2_.currency_id:BIGINT, merchantst2_.currency_format_national:BIT, merchantst2_.language_id:INT, merchantst2_.domain_name:VARCHAR, merchantst2_.in_business_since:DATE, merchantst2_.invoice_template:VARCHAR, merchantst2_.parent_id:INT, merchantst2_.is_retailer:BIT, merchantst2_.seizeunitcode:VARCHAR, merchantst2_.store_email:VARCHAR, merchantst2_.store_logo:VARCHAR, merchantst2_.store_template:VARCHAR, merchantst2_.store_address:VARCHAR, merchantst2_.store_city:VARCHAR, merchantst2_.store_name:VARCHAR, merchantst2_.store_phone:VARCHAR, merchantst2_.store_postal_code:VARCHAR, merchantst2_.store_state_prov:VARCHAR, merchantst2_.use_cache:BIT, merchantst2_.weightunitcode:VARCHAR, merchantst2_.zone_id:BIGINT}
}
