site:
  datasource_driver: com.mysql.jdbc.Driver
  datasource_url: jdbc:mysql://127.0.0.1:3306/pybbs_ys?autoReconnect=true&useLocalSessionState=true&readOnlyPropagatesToServer=false&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  datasource_username: admin
  datasource_password: password

# 想看mybatis执行的sql的时候，去掉下面这段的注释
# mybatis-plus:
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl