DROP PROCEDURE IF EXISTS `AddCart_sp_4_ver0`;
DELIMITER $$
CREATE PROCEDURE AddCart_sp_4_ver0 (IN RS_q10_r1_col1 INT)
BEGIN

DECLARE QUERY_ID_0_TXN INT DEFAULT NULL;
DECLARE QUERY_ID_1_TXN INT DEFAULT NULL;
DECLARE q3_i1 BIGINT DEFAULT NULL;
DECLARE QUERY_ID_2 INT DEFAULT NULL;
DECLARE M_I_RS_14_size INT DEFAULT NULL;
DECLARE cursor_cnt_2 INT DEFAULT NULL;

IF TRUE THEN
commit;
END IF;
IF TRUE THEN
SET QUERY_ID_0_TXN = 0;
set autocommit=1;
END IF;
IF TRUE THEN
SET QUERY_ID_1_TXN = 1;
set autocommit=0;
END IF;
IF TRUE THEN
SET q3_i1 = RS_q10_r1_col1;
SET QUERY_ID_2 = 2;
SELECT shoppingca0_.SHP_CART_ID AS SHP_CART1_69_0_, lineitems1_.SHP_CART_ITEM_ID AS SHP_CART1_71_1_, attributes2_.SHP_CART_ATTR_ITEM_ID AS SHP_CART1_70_2_, merchantst3_.MERCHANT_ID AS MERCHANT1_29_3_, shoppingca0_.DATE_CREATED AS DATE_CRE2_69_0_ , shoppingca0_.DATE_MODIFIED AS DATE_MOD3_69_0_, shoppingca0_.UPDT_ID AS UPDT_ID4_69_0_, shoppingca0_.CUSTOMER_ID AS CUSTOMER5_69_0_, shoppingca0_.IP_ADDRESS AS IP_ADDRE6_69_0_, shoppingca0_.MERCHANT_ID AS MERCHAN11_69_0_ , shoppingca0_.ORDER_ID AS ORDER_ID7_69_0_, shoppingca0_.PROMO_ADDED AS PROMO_AD8_69_0_, shoppingca0_.PROMO_CODE AS PROMO_CO9_69_0_, shoppingca0_.SHP_CART_CODE AS SHP_CAR10_69_0_, lineitems1_.DATE_CREATED AS DATE_CRE2_71_1_ , lineitems1_.DATE_MODIFIED AS DATE_MOD3_71_1_, lineitems1_.UPDT_ID AS UPDT_ID4_71_1_, lineitems1_.PRODUCT_ID AS PRODUCT_5_71_1_, lineitems1_.QUANTITY AS QUANTITY6_71_1_, lineitems1_.SHP_CART_ID AS SHP_CART7_71_1_ , lineitems1_.SHP_CART_ID AS SHP_CART7_71_0__, lineitems1_.SHP_CART_ITEM_ID AS SHP_CART1_71_0__, attributes2_.DATE_CREATED AS DATE_CRE2_70_2_, attributes2_.DATE_MODIFIED AS DATE_MOD3_70_2_, attributes2_.UPDT_ID AS UPDT_ID4_70_2_ , attributes2_.PRODUCT_ATTR_ID AS PRODUCT_5_70_2_, attributes2_.SHP_CART_ITEM_ID AS SHP_CART6_70_2_, attributes2_.SHP_CART_ITEM_ID AS SHP_CART6_70_1__, attributes2_.SHP_CART_ATTR_ITEM_ID AS SHP_CART1_70_1__, merchantst3_.DATE_CREATED AS DATE_CRE2_29_3_ , merchantst3_.DATE_MODIFIED AS DATE_MOD3_29_3_, merchantst3_.UPDT_ID AS UPDT_ID4_29_3_, merchantst3_.STORE_CODE AS STORE_CO5_29_3_, merchantst3_.CONTINUESHOPPINGURL AS CONTINUE6_29_3_, merchantst3_.COUNTRY_ID AS COUNTRY24_29_3_ , merchantst3_.CURRENCY_ID AS CURRENC25_29_3_, merchantst3_.CURRENCY_FORMAT_NATIONAL AS CURRENCY7_29_3_, merchantst3_.LANGUAGE_ID AS LANGUAG26_29_3_, merchantst3_.DOMAIN_NAME AS DOMAIN_N8_29_3_, merchantst3_.IN_BUSINESS_SINCE AS IN_BUSIN9_29_3_ , merchantst3_.INVOICE_TEMPLATE AS INVOICE10_29_3_, merchantst3_.PARENT_ID AS PARENT_27_29_3_, merchantst3_.IS_RETAILER AS IS_RETA11_29_3_, merchantst3_.SEIZEUNITCODE AS SEIZEUN12_29_3_, merchantst3_.STORE_EMAIL AS STORE_E13_29_3_ , merchantst3_.STORE_LOGO AS STORE_L14_29_3_, merchantst3_.STORE_TEMPLATE AS STORE_T15_29_3_, merchantst3_.STORE_ADDRESS AS STORE_A16_29_3_, merchantst3_.STORE_CITY AS STORE_C17_29_3_, merchantst3_.STORE_NAME AS STORE_N18_29_3_ , merchantst3_.STORE_PHONE AS STORE_P19_29_3_, merchantst3_.STORE_POSTAL_CODE AS STORE_P20_29_3_, merchantst3_.STORE_STATE_PROV AS STORE_S21_29_3_, merchantst3_.USE_CACHE AS USE_CAC22_29_3_, merchantst3_.WEIGHTUNITCODE AS WEIGHTU23_29_3_ , merchantst3_.ZONE_ID AS ZONE_ID28_29_3_ FROM SHOPPING_CART shoppingca0_ LEFT JOIN SHOPPING_CART_ITEM lineitems1_ ON shoppingca0_.SHP_CART_ID = lineitems1_.SHP_CART_ID LEFT JOIN SHOPPING_CART_ATTR_ITEM attributes2_ ON lineitems1_.SHP_CART_ITEM_ID = attributes2_.SHP_CART_ITEM_ID INNER JOIN MERCHANT_STORE merchantst3_ ON shoppingca0_.MERCHANT_ID = merchantst3_.MERCHANT_ID WHERE shoppingca0_.CUSTOMER_ID = q3_i1;
SET M_I_RS_14_size = FOUND_ROWS();
END IF;
SELECT QUERY_ID_0_TXN,QUERY_ID_1_TXN,QUERY_ID_2,q3_i1;

END $$
DELIMITER ;