DROP PROCEDURE IF EXISTS `Purchase_sp_8_ver0`;
DELIMITER $$
CREATE PROCEDURE Purchase_sp_8_ver0 ()
BEGIN

DECLARE QUERY_ID_0 INT DEFAULT NULL;
DECLARE M_I_RS_10_size INT DEFAULT NULL;
DECLARE cursor_cnt_0 INT DEFAULT NULL;

IF TRUE THEN
SET QUERY_ID_0 = 0;
SELECT language0_.LANGUAGE_ID AS LANGUAGE1_23_, language0_.DATE_CREATED AS DATE_CRE2_23_, language0_.DATE_MODIFIED AS DATE_MOD3_23_, language0_.UPDT_ID AS UPDT_ID4_23_, language0_.CODE AS CODE5_23_ , language0_.SORT_ORDER AS SORT_ORD6_23_ FROM LANGUAGE language0_;
SET M_I_RS_10_size = FOUND_ROWS();
END IF;
SELECT QUERY_ID_0;

END $$
DELIMITER ;