SqlNo=93
SQLNode {
    sqlTemplate='INSERT INTO ORDER_PRODUCT_PRICE (DEFAULT_PRICE, ORDER_PRODUCT_ID, PRODUCT_PRICE, PRODUCT_PRICE_CODE, PRODUCT_PRICE_NAME , PRODUCT_PRICE_SPECIAL, PRD_PRICE_SPECIAL_END_DT, PRD_PRICE_SPECIAL_ST_DT, ORDER_PRODUCT_PRICE_ID) VALUES (?, ?, ?, ?, ? , ?, ?, ?, ?)',
    parameters={RS_q53_r6_col8:BIT, (RS_q71_r1_col1 * 50):BIGINT, c_decimal($BIG_DECIMAL$RS_q19_r1_col71_intCompact$BIG_DECIMAL$, $BIG_DECIMAL$RS_q19_r1_col71_scale$BIG_DECIMAL$):DECIMAL, RS_q19_r1_col68:VARCHAR, RS_q19_r1_col83:VARCHAR, NULL:DECIMAL, NULL:DATETIME, NULL:DATETIME, (RS_q76_r1_col1 * 50):BIGINT},
    retVals={}
}
