DROP PROCEDURE IF EXISTS `Purchase_sp_50_ver0`;
DELIMITER $$
CREATE PROCEDURE Purchase_sp_50_ver0 (IN RS_q61_r1_col1 INT)
BEGIN

DECLARE q1_i1 BIGINT DEFAULT NULL;
DECLARE q1_i2 BIGINT DEFAULT NULL;
DECLARE QUERY_ID_0 INT DEFAULT NULL;
DECLARE M_I_RS_1162_rowCount INT DEFAULT NULL;
DECLARE cursor_cnt_0 INT DEFAULT NULL;

IF TRUE THEN
SET q1_i1 = (RS_q61_r1_col1+1);
SET q1_i2 = RS_q61_r1_col1;
SET QUERY_ID_0 = 0;
SAVEPOINT trace0_p2;
UPDATE SM_SEQUENCER SET SEQ_COUNT = q1_i1 WHERE SEQ_COUNT = q1_i2 AND SEQ_NAME = 'ORDER_ID_SEQ_NEXT_VAL';
SET M_I_RS_1162_rowCount = ROW_COUNT();
SELECT M_I_RS_1162_rowCount;
END IF;
SELECT QUERY_ID_0,q1_i1,q1_i2;

END $$
DELIMITER ;