DROP PROCEDURE IF EXISTS `Purchase_sp_42_ver0`;
DELIMITER $$
CREATE PROCEDURE Purchase_sp_42_ver0 ()
BEGIN

DECLARE q1_i1 VARCHAR(512) DEFAULT NULL;
DECLARE QUERY_ID_0 INT DEFAULT NULL;
DECLARE M_I_RS_53_size INT DEFAULT NULL;
DECLARE cursor_cnt_0 INT DEFAULT NULL;

IF TRUE THEN
SET q1_i1 = 'PAYMENT';
SET QUERY_ID_0 = 0;
SELECT integratio0_.MODULE_CONF_ID AS MODULE_C1_30_, integratio0_.DATE_CREATED AS DATE_CRE2_30_, integratio0_.DATE_MODIFIED AS DATE_MOD3_30_, integratio0_.UPDT_ID AS UPDT_ID4_30_, integratio0_.CODE AS CODE5_30_ , integratio0_.DETAILS AS DETAILS6_30_, integratio0_.CONFIGURATION AS CONFIGUR7_30_, integratio0_.CUSTOM_IND AS CUSTOM_I8_30_, integratio0_.IMAGE AS IMAGE9_30_, integratio0_.MODULE AS MODULE10_30_ , integratio0_.REGIONS AS REGIONS11_30_, integratio0_.TYPE AS TYPE12_30_ FROM MODULE_CONFIGURATION integratio0_ WHERE integratio0_.MODULE = q1_i1;
SET M_I_RS_53_size = FOUND_ROWS();
END IF;
SELECT QUERY_ID_0,q1_i1;

END $$
DELIMITER ;