DROP PROCEDURE IF EXISTS `AddCart_sp_24_ver0`;
DELIMITER $$
CREATE PROCEDURE AddCart_sp_24_ver0 ()
BEGIN

DECLARE QUERY_ID_0 INT DEFAULT NULL;
DECLARE M_I_RS_31_size INT DEFAULT NULL;
DECLARE cursor_cnt_0 INT DEFAULT NULL;

IF TRUE THEN
SET QUERY_ID_0 = 0;
SELECT SEQ_COUNT FROM SM_SEQUENCER WHERE SEQ_NAME = 'SHP_CRT_ITM_SEQ_NEXT_VAL' FOR UPDATE;
SET M_I_RS_31_size = FOUND_ROWS();
END IF;
SELECT QUERY_ID_0;

END $$
DELIMITER ;