DROP PROCEDURE IF EXISTS `Purchase_sp_33_ver0`;
DELIMITER $$
CREATE PROCEDURE Purchase_sp_33_ver0 (IN RS_q2_r1_col3 INT)
BEGIN

DECLARE QUERY_ID_0_TXN INT DEFAULT NULL;
DECLARE QUERY_ID_1_TXN INT DEFAULT NULL;
DECLARE q3_i1 INT DEFAULT NULL;
DECLARE QUERY_ID_2 INT DEFAULT NULL;
DECLARE M_I_RS_110_size INT DEFAULT NULL;
DECLARE cursor_cnt_2 INT DEFAULT NULL;

IF TRUE THEN
commit;
END IF;
IF TRUE THEN
SET QUERY_ID_0_TXN = 0;
set autocommit=1;
END IF;
IF TRUE THEN
SET QUERY_ID_1_TXN = 1;
set autocommit=0;
END IF;
IF TRUE THEN
SET q3_i1 = RS_q2_r1_col3;
SET QUERY_ID_2 = 2;
SELECT country0_.COUNTRY_ID AS COUNTRY_1_6_0_, descriptio1_.DESCRIPTION_ID AS DESCRIPT1_7_1_, country0_.GEOZONE_ID AS GEOZONE_4_6_0_, country0_.COUNTRY_ISOCODE AS COUNTRY_2_6_0_, country0_.COUNTRY_SUPPORTED AS COUNTRY_3_6_0_ , descriptio1_.DATE_CREATED AS DATE_CRE2_7_1_, descriptio1_.DATE_MODIFIED AS DATE_MOD3_7_1_, descriptio1_.UPDT_ID AS UPDT_ID4_7_1_, descriptio1_.DESCRIPTION AS DESCRIPT5_7_1_, descriptio1_.LANGUAGE_ID AS LANGUAGE8_7_1_ , descriptio1_.NAME AS NAME6_7_1_, descriptio1_.TITLE AS TITLE7_7_1_, descriptio1_.COUNTRY_ID AS COUNTRY_9_7_1_, descriptio1_.COUNTRY_ID AS COUNTRY_9_7_0__, descriptio1_.DESCRIPTION_ID AS DESCRIPT1_7_0__ FROM COUNTRY country0_ LEFT JOIN COUNTRY_DESCRIPTION descriptio1_ ON country0_.COUNTRY_ID = descriptio1_.COUNTRY_ID WHERE descriptio1_.LANGUAGE_ID = q3_i1;
SET M_I_RS_110_size = FOUND_ROWS();
END IF;
SELECT QUERY_ID_0_TXN,QUERY_ID_1_TXN,QUERY_ID_2,q3_i1;

END $$
DELIMITER ;